#version: '3.8'
services:
  api-escalamiento-principal:
    image: laurabm/api-escalamiento-principal:v1
    build: 
      context: .
    ports:
      - "5011:5011"  # Puerto de la API
    networks:
      - api-escalamiento-proyecto-servicio_api-escalamiento-net
    
networks: 
  api-escalamiento-proyecto-servicio_api-escalamiento-net:
    external: true